// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: balance_history.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBalanceHistory = `-- name: InsertBalanceHistory :exec
INSERT INTO balances_histories(balance_id, transaction_id, balance_amount_before, balance_amount_after) VALUES($1, $2, $3, $4)
`

type InsertBalanceHistoryParams struct {
	BalanceID           pgtype.UUID    `db:"balance_id" json:"balance_id"`
	TransactionID       pgtype.UUID    `db:"transaction_id" json:"transaction_id"`
	BalanceAmountBefore pgtype.Numeric `db:"balance_amount_before" json:"balance_amount_before"`
	BalanceAmountAfter  pgtype.Numeric `db:"balance_amount_after" json:"balance_amount_after"`
}

func (q *Queries) InsertBalanceHistory(ctx context.Context, arg InsertBalanceHistoryParams) error {
	_, err := q.db.Exec(ctx, insertBalanceHistory,
		arg.BalanceID,
		arg.TransactionID,
		arg.BalanceAmountBefore,
		arg.BalanceAmountAfter,
	)
	return err
}
