// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	InsertBalanceHistory(ctx context.Context, arg InsertBalanceHistoryParams) error
	InsertDefaultBalance(ctx context.Context, userID pgtype.UUID) error
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	InsertTopUp(ctx context.Context, arg InsertTopUpParams) (Topup, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
	InsertTransfer(ctx context.Context, arg InsertTransferParams) (Transfer, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	SelectOneUserById(ctx context.Context, userID pgtype.UUID) (SelectOneUserByIdRow, error)
	SelectOneUserByPhoneNumber(ctx context.Context, phoneNumber string) (SelectOneUserByPhoneNumberRow, error)
	SelectTransactionByUserId(ctx context.Context, userID pgtype.UUID) ([]SelectTransactionByUserIdRow, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
