// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: topup.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTopUp = `-- name: InsertTopUp :one
INSERT INTO topups(user_id, top_up_amount) VALUES($1, $2) RETURNING top_up_id, user_id, top_up_amount, created_at, updated_at
`

type InsertTopUpParams struct {
	UserID      pgtype.UUID    `db:"user_id" json:"user_id"`
	TopUpAmount pgtype.Numeric `db:"top_up_amount" json:"top_up_amount"`
}

func (q *Queries) InsertTopUp(ctx context.Context, arg InsertTopUpParams) (Topup, error) {
	row := q.db.QueryRow(ctx, insertTopUp, arg.UserID, arg.TopUpAmount)
	var i Topup
	err := row.Scan(
		&i.TopUpID,
		&i.UserID,
		&i.TopUpAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
